### PR TITLE
Copy Dispatch and Clang from upstream toolchain

### LINKED ISSUE #713: SwiftPM doesn't work in the Linux build
SwiftPM works fine in the macOS build of our toolchain, but it fails in the Linux build as can be seen in [this WASFoundation CI run](https://github.com/MaxDesiatov/WASIFoundation/runs/599633497?check_suite_focus=true):

```
+ swift build
/github/workspace: error: manifest parse error(s):
<unknown>:0: error: cannot load underlying module for 'Dispatch'
```

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Resolve #713. This should copy modulemaps and headers and shouldn't overwrite any wasm libraries. `clang` binaries are now longer copied from the upstream snapshot instead of `wasi-sdk`, as the latter can't builf for host architectures (at least on Linux).

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
It finally works! 🎉 I've got the last artifact package in the `swiftwasm-action` Docker image, which now allows us to get [working SwiftWasm GitHub Actions](https://github.com/MaxDesiatov/Runtime/pull/3/checks?check_run_id=649269501)!

File: utils/webassembly/build-toolchain.sh [hunk 1]
```diff
@@ -73,7 +74,7 @@ sed -i -e "s@\".*/include@\"../../../../share/wasi-sysroot/include@g" $TMP_DIR/$
 # Copy nightly-toolchain's host environment stdlib into toolchain
 
 if [[ "$(uname)" == "Linux" ]]; then
-  cp -r $NIGHTLY_TOOLCHAIN/usr/lib/swift/linux $TMP_DIR/$TOOLCHAIN_NAME/usr/lib/swift
+  cp -a $NIGHTLY_TOOLCHAIN/usr/lib/* $TMP_DIR/$TOOLCHAIN_NAME/usr/lib || true
```
Comment (kateinoigakukun) [inline utils/webassembly/build-toolchain.sh:77]: I'm not sure why need `|| true` :thinking:

File: utils/webassembly/build-toolchain.sh [hunk 2]
```diff
@@ -61,7 +61,8 @@ cd $TMP_DIR/$TOOLCHAIN_NAME
 
 # Merge wasi-sdk and toolchain
 cp -r $WASI_SDK_PATH/lib/clang usr/lib
-cp $WASI_SDK_PATH/bin/* usr/bin
+cp -a $SOURCE_PATH/build/Ninja-ReleaseAssert/llvm-*/bin/clang* usr/bin
```
Comment (kateinoigakukun) [inline utils/webassembly/build-toolchain.sh:64]: Please use `--llvm-install-components` instead of depending on build directory path :pray:
https://gist.github.com/kateinoigakukun/af8226e41a6db4d12706d8faa187cf3b

File: utils/webassembly/build-toolchain.sh (hunk 1 above)
Comment (MaxDesiatov) [reply utils/webassembly/build-toolchain.sh:77]: There's a single file that fails to get copied, related to clang I think. It doesn't cause problems as far as I understand, and it's a pain to test and to exclude just a single file. I can add a comment about that in the script. Not sure I'll be able to get the exact file name quickly, seems like GitHub erased logs for the previous actions in this PR (maybe because of the force push?), and I don't have access to powerful hardware to re-run builds quickly from scratch.

Comment (kateinoigakukun) [reply utils/webassembly/build-toolchain.sh:77]: OK, I'll try it on my local machine 👍

Comment (kateinoigakukun) [reply utils/webassembly/build-toolchain.sh]: I got the error. It seems that our toolchain's `lib/swift/clang` is a directory but nightly toolchain's one is a symlink.
```
cp: cannot overwrite directory '/tmp/tmp.wtHPlnPXwh/swift-wasm-DEVELOPMENT-SNAPSHOT-2020-05-06-a/usr/lib/swift/clang' with non-directory
```

So I added `clang-resource-dir-symlink` component to install to create that symlink

**Comment by MaxDesiatov** [comment]
The Linux build is failing now with this weird error 🤔 `clang: error: unable to execute command: Killed`

**Comment by kateinoigakukun** [comment]
@MaxDesiatov Could you check the latest toolchain with my commit work well on the docker image?

**Comment by MaxDesiatov** [comment]
Will do, thanks for the updates!
